### ISSUE TITLE
CUSA12878 - Beat Saber

### ISSUE THREAD

**Issue by Nawafmoe** [shadps4-emu/shadps4-game-compatibility#1486] opened 2024-12-26 11:38 UTC
### Game Name

Beat Saber

### Game code

CUSA12878

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Boots

### Operating System

Windows

### Error

black screen after beat games and made with unity splashes

### Description

it doesn't crash, just shows the splashes and then the blackscreen, probably because what comes next should appear in vr which is not implemented

### Screenshots

![{7E9218E1-84A8-424C-B3EC-1E3E36E56A0B}](https://github.com/user-attachments/assets/20715f09-bec6-4e62-976f-a9db2347d773)
![{D21AD272-98AC-4556-A064-E0ADFB1CCB95}](https://github.com/user-attachments/assets/81c7f8a8-d462-43e0-ba75-0274924a8eba)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18252450/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-26 13:53
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/491

**Comment by Hermiten** [comment] 2024-12-26 13:53
Please update by comment here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/491

**Closed by Hermiten** 2024-12-26 13:53 UTC
