### ISSUE TITLE
CUSA00082 - Anomaly 2

### ISSUE THREAD

**Issue by gamecoreSRC** [shadps4-emu/shadps4-game-compatibility#739] opened 2024-09-30 08:35 UTC
### Game Name

Anomaly 2

### Game code

CUSA00082

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.3.0 

### Current status

Nothing

### Operating System

Windows

### Error

Attempts to load up trophies seemingly but errors;
`[Lib.NpTrophy] <Info> np_trophy.cpp:sceNpTrophyCreateHandle:185: New handle = 0`
`[Lib.NpTrophy] <Info> np_trophy.cpp:sceNpTrophyDestroyHandle:216: Handle 0 destroyed`
`[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceUltQueuePop (nid: RVSq2tsm2yw) called, returning zero to 0x9004527af`

### Description

It boots to a black screen without rendering anything whilst the console seems to try to start up the trophies (possible) before it crashes.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17186543/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-03 14:43
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/166

**Closed by Hermiten** 2024-12-03 14:43 UTC
