### ISSUE TITLE
CUSA00062 - Alienation

### ISSUE THREAD

**Issue by hq5566** [shadps4-emu/shadps4-game-compatibility#814] opened 2024-10-04 22:31 UTC
### Game Name

Alienation

### Game code

CUSA00062

### Game version

v1.06

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Nothing

### Operating System

Windows

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceImeUpdate (nid: -4GCfYdNF1s) called, returning zero to 0x9012a06d8

### Description

black screen. cannot boot.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17264273/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-03 14:13
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/10

**Closed by Hermiten** 2024-12-03 14:13 UTC
Labels: status-nothing, os-windows
