### ISSUE TITLE
CUSA11454 - Control

### ISSUE THREAD

**Issue by danoka29** [shadps4-emu/shadps4-game-compatibility#750] opened 2024-10-01 18:01 UTC
### Game Name

Control

### Game code

CUSA11454

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Nothing

### Operating System

Windows

### Error

[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type Interpreter Path
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Comment
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Loader] <Error> memory_patcher.cpp:OnGameLoaded:199: Unable to open files.json for reading.
[Loader] <Error> memory_patcher.cpp:OnGameLoaded:199: Unable to open files.json for reading.
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Comment
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:194: Unimplemented type SCE Library Version
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved E4BqY+tbRqY as Unknown !!! (lib: rl_ps4_f, mod: rl_ps4_f)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved wqWqhvgoDjc as Unknown !!! (lib: rl_ps4_f, mod: rl_ps4_f)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved adMmMiKD7-o as Unknown !!! (lib: rl_ps4_f, mod: rl_ps4_f)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved QyldQFIcYnk as Unknown !!! (lib: rl_ps4_f, mod: rl_ps4_f)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved pym34IIOsAc as Unknown !!! (lib: rl_ps4_f, mod: rl_ps4_f)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved usXUuvmKZLM as Unknown !!! (lib: coregame_ps4_f, mod: coregame_ps4_f)

### Description

spews errors for a while on a black screen and then crashes

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17214032/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-03 14:29
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/250

**Closed by Hermiten** 2024-12-03 14:29 UTC

**Comment by 123qxzhj** [comment] 2025-01-21 15:11
Emu version: 0.5.0
Status: Boots

```
[Kernel.Vmm] <Warning> memory.cpp:sceKernelGetDirectMemorySize:22: called
[Kernel.Vmm] <Info> memory.cpp:sceKernelAvailableFlexibleMemorySize:251: called size = 0xb6ac000
[Kernel.Vmm] <Warning> memory.cpp:sceKernelGetDirectMemorySize:22: called
[Kernel.Vmm] <Info> memory.cpp:sceKernelAvailableFlexibleMemorySize:251: called size = 0xb6ac000
```

[shad_log.zip](https://github.com/user-attachments/files/18492767/shad_log.zip)

Crashes after last screen.

![Image](https://github.com/user-attachments/assets/8b9eaf65-61f1-4379-a5e7-f0f2a86e3f12)
![Image](https://github.com/user-attachments/assets/3e0fd748-7c3a-42bd-8869-9f4de7b9b888)
![Image](https://github.com/user-attachments/assets/b935d729-4d1f-4e51-9c71-0b4dc155c0fb)
![Image](https://github.com/user-attachments/assets/4679c4f3-c8ca-4d7c-b063-7e1394bdf924)
