### ISSUE TITLE
Lego Dimensions (CUSA00935)

### ISSUE THREAD

**Issue by carlosgamer23** [shadps4-emu/shadps4-game-compatibility#1359] opened 2024-12-09 16:51 UTC
### Game Name

Lego Dimensions

### Game code

CUSA00935

### Game version

I don't know if the US version has an update, I think only the EUR version received it because of its additional languages.

### Used emulator's version (only released versions are acceptable)

0.4.1 (If I'm not mistaken this is the most current one, I always update it anyway)

### Current status

Nothing

### Operating System

Windows

### Error

The Lego Dimensions game does not start and closes the emulator brutally, I must warn you that the LEGO engine is really terrible, many emulators have problems with it, but I wish good luck to your team. By the way, Godzilla for PS4 It's entering the loading screen and closing, but I congratulate you because this is already a big step, shadps4 will certainly be more accurate than RPCS3 thanks to your efforts, congratulations! 🤩

### Description

The Lego Dimensions game does not start and closes the emulator brutally, I must warn you that the LEGO engine is really terrible, many emulators have problems with it, but I wish good luck to your team. By the way, Godzilla for PS4 It's entering the loading screen and closing, but I congratulate you because this is already a big step, shadps4 will certainly be more accurate than RPCS3 thanks to your efforts, congratulations! 🤩

### Log File

I'm currently writing this on my cell phone, but I'll look at it later on my computer and put it in the comments somehow. (I'm sorry for my lack of preparation 😅)

**Comment by Hermiten** [comment] 2024-12-10 09:25
Thanks for this good report !
But we only accept on major release like 0.4 and not 0.4.1
Also this is duplicate of this one:
https://github.com/shadps4-emu/shadps4-game-compatibility/issues/81

**Comment by Hermiten** [comment] 2024-12-10 09:26
You can try on 0.4 and update on the original one

**Closed by Hermiten** 2024-12-10 09:25 UTC
