### ISSUE TITLE
CUSA36891 - The Bookwalker

### ISSUE THREAD

**Issue by gamecoreSRC** [shadps4-emu/shadps4-game-compatibility#736] opened 2024-09-30 07:29 UTC
### Game Name

The Bookwalker

### Game code

CUSA36891

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Nothing

### Operating System

Windows

### Error

Possibly:
`[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_APP_CONTENT`
`[Lib.AppContent] <Error> app_content.cpp:sceAppContentInitialize:246: (DUMMY) called`
`[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_APP_CONTENT`
`[Lib.AppContent] <Error> app_content.cpp:sceAppContentInitialize:246: (DUMMY) called`

### Description

Crashes after launching with some errors thrown in the console.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17185731/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-03 14:41
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/498

**Closed by Hermiten** 2024-12-03 14:41 UTC
