### ISSUE TITLE
CUSA00402 - Crimsonland

### ISSUE THREAD

**Issue by gamecoreSRC** [shadps4-emu/shadps4-game-compatibility#769] opened 2024-10-01 22:09 UTC
### Game Name

Crimsonland

### Game code

CUSA00402

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Nothing

### Operating System

Windows

### Error

I can't really tell what the error is.

### Description

It crashes for some reason, though I'm not exactly sure why.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17217128/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-03 14:35
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/169

**Closed by Hermiten** 2024-12-03 14:35 UTC
