### ISSUE TITLE
CUSA36842 - Red Dead Redemption

### ISSUE THREAD

**Issue by DLADAnaconda** [shadps4-emu/shadps4-game-compatibility#1510] opened 2024-12-26 15:48 UTC
### Game Name

Red Dead Redemption

### Game code

CUSA36842

### Game version

01.04

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Boots

### Operating System

Windows

### Error

Tried to run the game today after seeing this game update with ShadPS5 on Windows 11, Geforce GTX 1060 (mobile). The game crashes right after accepting license agreements. 
Booting a couple more times after accepting the license agreements, sometimes the game crashes right after the first disclaimer and sometimes, the game remains on black screen after the second disclaimer prompt

### Description

Tried to run the game today after seeing this game update with ShadPS5 on Windows 11, Geforce GTX 1060 (mobile). The game crashes right after accepting license agreements. 
Booting a couple more times after accepting the license agreements, sometimes the game crashes right after the first disclaimer and sometimes, the game remains on black screen after the second disclaimer prompt

### Screenshots

![shadPS4_l58iiqeXVz](https://github.com/user-attachments/assets/77a1ac88-d4fe-422f-9fd4-54e1c7875fbd)
![shadPS4_HUMiQpNg3k](https://github.com/user-attachments/assets/55c56718-1590-4e1b-9118-a5a4891661b7)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18253837/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-26 16:11
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1390

**Comment by Hermiten** [comment] 2024-12-26 16:12
Please update by comment here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1390

**Closed by Hermiten** 2024-12-26 16:12 UTC

**Comment by Hermiten** [comment] 2024-12-26 16:17
And sorry, I didn't see about the duplicate when I told you to open a new one

**Comment by DLADAnaconda** [comment] 2024-12-26 16:41
> And sorry, I didn't see about the duplicate when I told you to open a new one

Fixed.
