### ISSUE TITLE
CUSA08652 - Wreckfest

### ISSUE THREAD

**Issue by ThunderNowX** [shadps4-emu/shadps4-game-compatibility#1431] opened 2024-12-25 21:12 UTC
### Game Name

Wreckfest

### Game code

CUSA08652

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

Black Screen

### Description

Compared to 0.4.0, is not booting, black screen! Is a mess

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18247209/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-25 21:25
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1293
Please update here

**Closed by Hermiten** 2024-12-25 21:25 UTC

**Comment by ThunderNowX** [comment] 2024-12-25 21:29
What i have to update here

**Comment by ThunderNowX** [comment] 2024-12-25 21:31
New Shad Log 0.5.0
[shad_log.txt](https://github.com/user-attachments/files/18247255/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-25 21:47
Sorry, update here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1293
