### ISSUE TITLE
CUSA33872 - Persona 3 Portable

### ISSUE THREAD

**Issue by GoldenPixelYT** [shadps4-emu/shadps4-game-compatibility#569] opened 2024-09-08 04:45 UTC
### Game Name

Persona 3 Portable

### Game code

CUSA33872

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Boots

### Error

[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:393: Unsupported tiled image: R8G8B8A8Unorm (Display_Linear)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:393: Unsupported tiled image: R8G8B8A8Srgb (Display_MacroTiled)
[Render.Vulkan] <Info> renderer_vulkan.cpp:GetRenderFrame:357: Got render frame, remaining 0
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitDone:2139: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitAndFlipCommandBuffers:2039: called [buf = 0]
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called

### Description

Game boots slowly to Atlus logo then hangs.

### Screenshots

![Screenshot 2024-09-07 235254](https://github.com/user-attachments/assets/3c628d12-c8c1-4e9a-9d53-deb5a19d3743)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16920874/shad_log.txt)

**Comment by TheCoolPup** [comment] 2024-09-08 21:26
confirmed playable on the latest action build.

**Comment by LukeWarnut** [comment] 2024-09-09 20:36
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/187

**Comment by georgemoralis** [comment] 2024-09-10 08:10
duplicate

**Closed by georgemoralis** 2024-09-10 08:10 UTC
