### ISSUE TITLE
CUSA00063 - LittleBigPlanet 3

### ISSUE THREAD

**Issue by Crispy81** [shadps4-emu/shadps4-game-compatibility#1195] opened 2024-11-22 22:12 UTC
### Game Name

LittleBigPlanet 3

### Game code

CUSA00063

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.4

### Current status

Nothing

### Operating System

Windows

### Error

.

### Description

Black screen. Emulator crashes and closes.

### Screenshots

![Screenshot 2024-11-23 090950](https://github.com/user-attachments/assets/44599d22-d2f7-49eb-8162-d0b853770427)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17876892/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-03 12:09
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/80

**Closed by Hermiten** 2024-12-03 12:09 UTC
