### ISSUE TITLE
CUSA01648 - FINAL FANTASY XV EPISODE DUSCAE

### ISSUE THREAD

**Issue by lemmeusethefuckingps4emu** [shadps4-emu/shadps4-game-compatibility#1319] opened 2024-11-30 12:56 UTC
### Game Name

FINAL FANTASY XV EPISODE DUSCAE

### Game code

CUSA01648

### Game version

v01.02

### Used emulator's version (only released versions are acceptable)

v0.4.0

### Current status

Nothing

### Operating System

Windows

### Error

Nothing happens. Same as Patch 1.00 for Episode Duscae.

### Description

No sound, menus anything. Straight black screen then crash after a few seconds.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17965448/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-03 13:02
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1318

**Closed by Hermiten** 2024-12-03 13:02 UTC
