### ISSUE TITLE
CUSA09559 - ONRUSH

### ISSUE THREAD

**Issue by Sambouza** [shadps4-emu/shadps4-game-compatibility#1317] opened 2024-11-30 10:18 UTC
### Game Name

ONRUSH

### Game code

CUSA09559

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.0

### Current status

Nothing

### Operating System

Windows

### Error

Error(s) can be found in log, this is just the end of the log.

```lua
[Lib.Net] <Error> net.cpp:sceNetInit:770: (DUMMY) called
[Lib.Net] <Error> net.cpp:sceNetSocket:1044: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSocketClose:1054: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSocket:1044: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetBind:124: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetListen:785: (STUBBED) called
[Lib.SystemService] <Error> systemservice.cpp:sceSystemServiceParamGetString:1931: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetGetsockname:684: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSocket:1044: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSocketClose:1054: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSocket:1044: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSetsockopt:954: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSetsockopt:954: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetBind:124: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSendto:929: (STUBBED) called
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCreate:1050: thread create name = HavokWorkerThread
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadSetschedparam:1492: (STUBBED) called policy=3, sched_priority=700
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCreate:1050: thread create name = HavokWorkerThread
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadSetschedparam:1492: (STUBBED) called policy=3, sched_priority=700
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCreate:1050: thread create name = HavokWorkerThread
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadSetschedparam:1492: (STUBBED) called policy=3, sched_priority=700
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCreate:1050: thread create name = HavokWorkerThread
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadSetschedparam:1492: (STUBBED) called policy=3, sched_priority=700
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/data/dat/2_GM_CO.dat flags = 0x0 mode = 365
[Core.Linker] <Error> linker.cpp:InitTlsForThread:379: TLS user malloc called, using std::malloc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_guard_acquire (nid: 3GPpjQdAMTw) called, returning zero to 0x9300560da
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_guard_acquire (nid: 3GPpjQdAMTw) called, returning zero to 0x9300560da
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_guard_acquire (nid: 3GPpjQdAMTw) called, returning zero to 0x9300560da
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_guard_acquire (nid: 3GPpjQdAMTw) called, returning zero to 0x930042e50
[Core.Linker] <Error> linker.cpp:InitTlsForThread:379: TLS user malloc called, using std::malloc
[Lib.NpManager] <Error> np_manager.cpp:sceNpSetContentRestriction:1970: (STUBBED) called
[Lib.UserService] <Info> userservice.cpp:sceUserServiceGetUserName:1071: called user_id = 1 ,size = 17 
[Lib.NpManager] <Error> np_manager.cpp:sceNpRegisterStateCallbackA:1950: (STUBBED) called
[Lib.NpManager] <Error> np_manager.cpp:sceNpRegisterNpReachabilityStateCallback:1935: (STUBBED) called
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNpWebApiCreateContextA (nid: zk6c65xoyO0) called, returning zero to 0x900034437
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNpWebApiCreateHandle (nid: 79M-JqvvGo0) called, returning zero to 0x900034453
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNpWebApiCreateExtdPushEventFilter (nid: M2BUB+DNEGE) called, returning zero to 0x9000345d3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNpWebApiRegisterExtdPushEventCallbackA (nid: jhXKGQJ4egI) called, returning zero to 0x9000345f9
[Lib.Pad] <Error> pad.cpp:scePadInit:203: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadOpen:248: (DUMMY) called user_id = 1 type = 0 index = 0
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_MOUSE
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMouseInit (nid: Qs0wWulgl7U) called, returning zero to 0x900061c33
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMouseOpen (nid: RaqxZIf6DvE) called, returning zero to 0x900061c50
[Core.Linker] <Error> linker.cpp:InitTlsForThread:379: TLS user malloc called, using std::malloc
[Core.Linker] <Error> linker.cpp:InitTlsForThread:379: TLS user malloc called, using std::malloc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x90011cc1e
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x90011cc2f
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x90012b67b
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x90013c9a3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90013ccf2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90012b694
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x90012b625
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_NP_COMMERCE
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_APP_CONTENT
[Lib.AppContent] <Error> app_content.cpp:sceAppContentInitialize:246: (DUMMY) called
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x90012afaf
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x90012b443
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90012b5df
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90012b3e0
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: socket (nid: TU-d9PfIHPM) called, returning zero to 0x90002f4d2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90012b62f
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90011cda4
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b5b5c
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b5e2a
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000b5e3e
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b94c7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000b5f5c
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b9650
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b96d3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000b972e
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000b97af
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b5f72
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000b5fe7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b98c0
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000b997a
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b6006
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b99cc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b9a09
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000b9a33
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90010f282
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000bc270
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000bc78d
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000ba7cc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000eeca6
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000eef5e
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000bd172
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000babfc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b9ef3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000bbd76
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000bc703
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000bac32
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000ba235
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000b9f78
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000b9fa2
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000ba31c
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000ba396
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000ba3af
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000ba48c
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPushMarker (nid: zw+celG7zSI) called, returning zero to 0x9000ba49d
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000ba5dc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90010f310
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x90010f282
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPopMarker (nid: YpkGsMXP3ew) called, returning zero to 0x9000bbd0b
```

### Description

Freezes & Crashes after ~1 second

### Screenshots

https://github.com/user-attachments/assets/3d249f47-5d49-4ee0-a07e-28c3acdd0e87

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17965033/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-03 13:02
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/216

**Closed by Hermiten** 2024-12-03 13:02 UTC
