### ISSUE TITLE
 Bloodborne Issue

### ISSUE THREAD

**Issue by L4RUS** [shadps4-emu/shadps4-game-compatibility#591] opened 2024-09-15 21:41 UTC
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

01.09

### Used emulator's version (only released versions are acceptable)

v0.2.1 WIP

### Current status

Menus

### Error

The game crashes just after the cutscene when there is a character creation menu.

### Description

PC crashes on Character Creation.

SPECS:
16gb RAM 
gtx 1650 4 gb
Intel Core I3-12100F 3.30 GHz

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17007492/shad_log.txt)

**Comment by StevenMiller123** [comment] 2024-09-16 19:08
Compatibility reports should only be made with release versions, not WIP builds. Additionally, this is a duplicate of report #71.

**Closed** 2024-09-19 05:32 UTC
