### ISSUE TITLE
CUSA13795 - Crash Team Racing Nitro Fueled

### ISSUE THREAD

**Issue by Ermahiho** [shadps4-emu/shadps4-game-compatibility#1614] opened 2024-12-28 22:53 UTC
### Game Name

Crash™ Team Racing Nitro-Fueled

### Game code

CUSA13795

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Boots

### Operating System

Linux

### Error

Can't play the game

### Description

Black screen on boot and after that shadPS4 crash

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18267930/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-28 22:59
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/960

**Comment by Hermiten** [comment] 2024-12-28 23:00
You can update with a comment on the other one

**Closed** 2024-12-28 23:00 UTC
