### ISSUE TITLE
CUSA08054 The Seven Deadly Sins Knights of Britannia

### ISSUE THREAD

**Issue by SalNaro** [shadps4-emu/shadps4-game-compatibility#1361] opened 2024-12-09 23:24 UTC
### Game Name

The Seven Deadly Sins Knights of Britannia

### Game code

CUSA08054

### Game version

v1.03

### Used emulator's version (only released versions are acceptable)

0.4.1

### Current status

Boot

### Operating System

Windows

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMoveReadStateRecent (nid: f2bcpK6kJfg) called, returning zero to 0x900e2a065
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMoveReadStateRecent (nid: f2bcpK6kJfg) called, returning zero to 0x900e2a065
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMoveReadStateRecent (nid: f2bcpK6kJfg) called, returning zero to 0x900e2a065
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMoveReadStateRecent (nid: f2bcpK6kJfg) called, returning zero to 0x900e2a065
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMoveReadStateRecent (nid: f2bcpK6kJfg) called, returning zero to 0x900e2a065
[Debug] <Critical> vk_scheduler.cpp:operator():147: Assertion Failed!
Device lost during submit

### Description

the game boots, but crash after the loading screen

### Screenshots

![Screenshot (295)](https://github.com/user-attachments/assets/5f7d5a0a-3d06-4ae0-82fd-8e839b42561b)
![Screenshot (298)](https://github.com/user-attachments/assets/33705706-a772-43e3-886a-f487f15daae2)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18069273/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-10 09:21
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/525
You can update the test on this link but in version 0.4, not 0.4.1

**Closed by Hermiten** 2024-12-10 09:21 UTC
