### ISSUE TITLE
CUSA06171 - Patapon Remastered

### ISSUE THREAD

**Issue by MarkusxD19** [shadps4-emu/shadps4-game-compatibility#1448] opened 2024-12-25 23:14 UTC
### Game Name

Patapon Remastered

### Game code

CUSA06171

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Ingame

### Operating System

Windows

### Error

[Lib.SystemService] <Info> systemservice.cpp:sceSystemServiceParamGetInt:1892: called param_id 1
[Tty] <Error> logger.cpp:log_flush:58: [stderr] INFO: (OSKPS4) Language code: 2

### Description

First Level is playable. Game always crashes after the first level at the name-screen before you could name your character and save your game. 

### Screenshots

<img width="635" alt="patapon4" src="https://github.com/user-attachments/assets/5927c204-2e29-487a-8256-6e2d6486a197" />
<img width="845" alt="pataponhd3" src="https://github.com/user-attachments/assets/14b8e641-f48f-435a-aafd-25da17bf1352" />

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18247406/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-26 09:25
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/140

**Comment by Hermiten** [comment] 2024-12-26 09:25
PLease update the statut of the gane by comment here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/140

**Closed by Hermiten** 2024-12-26 09:25 UTC
