### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by ahmed7072** [shadps4-emu/shadps4-game-compatibility#520] opened 2024-08-27 22:25 UTC
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

v.1.09

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Playable

### Error

liverpool.cpp:ProcessGraphics:463: Unreachable code!

### Description

game crashes after moving around in a minute or so

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16770176/shad_log.txt)

**Comment by Cyclizar** [comment] 2024-08-28 07:20
duplicate of #71 
0.2.1 isnt an official version
wrong title

**Closed** 2024-08-28 11:04 UTC
