### ISSUE TITLE
CUSA00054 - Mad Max

### ISSUE THREAD

**Issue by Francyemu226** [shadps4-emu/shadps4-game-compatibility#1638] opened 2024-12-29 18:16 UTC
### Game Name

Mad Max

### Game code

CUSA00054

### Game version

01.06

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Ingame

### Operating System

Windows

### Error

this error repeats...

[Lib.NpManager] <Error> np_manager.cpp:sceNpCheckNpAvailability:879: (STUBBED) called
[Lib.NpManager] <Error> np_manager.cpp:sceNpDeleteRequest:910: (DUMMY) called reqId = 3044
[Lib.NpManager] <Error> np_manager.cpp:sceNpCreateRequest:904: (DUMMY) called
[Lib.NpManager] <Error> np_manager.cpp:sceNpCheckNpAvailability:879: (STUBBED) called
[Lib.NpManager] <Error> np_manager.cpp:sceNpDeleteRequest:910: (DUMMY) called reqId = 3045

### Description

the game starts and loads the saved game

the graphics have problems with the textures

and after a while it crashed

### Screenshots

<img width="957" alt="Mad_Max_5" src="https://github.com/user-attachments/assets/ffaa67a4-cf30-49b6-8062-5fabf2a375b7" />

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18270473/shad_log.txt)

**Comment by C4ndyF1sh** [comment] 2024-12-29 18:22
duplicate of[ ](https://github.com/shadps4-emu/shadps4-game-compatibility/issues/239)

**Comment by Xphalnos** [comment] 2024-12-29 18:41
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/239. Please update by a comment.

**Closed by Xphalnos** 2024-12-29 18:41 UTC
