### ISSUE TITLE
CUSA06778 - Hidden Agenda

### ISSUE THREAD

**Issue by Viv1986** [shadps4-emu/shadps4-game-compatibility#1520] opened 2024-12-26 21:18 UTC
### Game Name

Hidden Agenda

### Game code

CUSA06778 

### Game version

v1.09

### Used emulator's version (only released versions are acceptable)

v0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Module Parameters
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Comment
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Library Version
[Core.Linker] <Error> linker.cpp:Resolve:273: Linker: Stub resolved V68cnNy5CT8 as Unknown !!! (lib: CoherentGTCore, mod: CoherentGTCore)
[Core.Linker] <Error> linker.cpp:Resolve:273: Linker: Stub resolved 8w4gFcXTELc as _ZN7WebCore12ChromeClient29supportsImmediateInvalidationEv (lib: CoherentGTCore, mod: CoherentGTCore)
[Core.Linker] <Error> linker.cpp:Resolve:273: Linker: Stub resolved xCp+mHd2wd0 as _ZNK7WebCore12ChromeClient35dispatchViewportPropertiesDidChangeERKNS_17ViewportArgumentsE (lib: CoherentGTCore, mod: CoherentGTCore)
[Core.Linker] <Error> linker.cpp:Resolve:273: Linker: Stub resolved R2P1XYnFLus as Unknown !!! (lib: CoherentGTCore, mod: CoherentGTCore)

### Description

Intel CPU 6700K
RTX 4060

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18255496/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-26 21:30
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1312

**Comment by Hermiten** [comment] 2024-12-26 21:30
Please update by comment here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1312

**Closed by Hermiten** 2024-12-26 21:30 UTC
