### ISSUE TITLE
CUSA03440 - Assassin’s Creed® Chronicles: Trilogy Pack

### ISSUE THREAD

**Issue by Quaii** [shadps4-emu/shadps4-game-compatibility#1514] opened 2024-12-26 17:02 UTC
### Game Name

Assassin’s Creed® Chronicles: Trilogy Pack

### Game code

CUSA03440

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Boots

### Operating System

Windows

### Error

not playable

### Description

only boot and gets stuck after intro

### Screenshots

![grafik](https://github.com/user-attachments/assets/732e0004-e290-4251-b833-5c1ad1030382)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18254262/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-26 21:28
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1085
Please update by comment here https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1085

**Closed by Hermiten** 2024-12-26 21:28 UTC
