### ISSUE TITLE
Rock Band 4 - CUSA02084

### ISSUE THREAD

**Issue by Birelso** [shadps4-emu/shadps4-game-compatibility#816] opened 2024-10-05 14:12 UTC
### Game Name

Rock Band 4

### Game code

CUSA02084

### Game version

v1.08

### Used emulator's version (only released versions are acceptable)

v0.30.0

### Current status

Menus

### Operating System

Windows

### Error

<Critical> structured_control_flow.cpp:operator():835: Assertion Failed!
Shader translation has failed

### Description

My game basically crashes when i boot up a song, my pc specs are:
Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40
NVIDIA GeForce GTX 1060 3GB
16 GB of ram

### Screenshots

![imagem_2024-10-05_111108182](https://github.com/user-attachments/assets/46a26d14-185c-4c4b-9506-5e7b19983c07)

### Log File

[Debug] <Critical> structured_control_flow.cpp:operator():835: Assertion Failed!
Shader translation has failed

**Comment by Hermiten** [comment] 2024-12-03 14:14
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/144

**Closed by Hermiten** 2024-12-03 14:14 UTC
